#pragma once

#ifndef SERIALPORT_GLOBAL_H
#define SERIALPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALLIB_LIBRARY)
#  define SERIALLIB_EXPORT Q_DECL_EXPORT
#else
#  define SERIALLIB_EXPORT Q_DECL_IMPORT
#endif

#define SERIALPORT_VER_MAJOR 0
#define SERIALPORT_VER_MINOR 0
#define SERIALPORT_VER_PATCH 1

#define SERIALPORT_TO_VERSION(major, minor, patch) (major * 10000 + minor * 100 + patch)
#define SERIALPORT_VERSION SERIALPORT_TO_VERSION(SERIALPORT_VER_MAJOR, SERIALPORT_VER_MINOR, SERIALPORT_VER_PATCH)


#endif // SERIALPORT_GLOBAL_H
